# Generated by Django 5.2.3 on 2025-06-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestoreEventi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
