# Generated by Django 5.2.3 on 2025-06-21 10:24

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestoreEventi', '0003_category_alter_event_date_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='event',
            name='is_free_event',
            field=models.BooleanField(default=False, verbose_name='free event'),
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(choices=[('EUR', '€'), ('BTC', '₿'), ('XMR', 'ɱ')], default='EUR', max_length=3, verbose_name='currency')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='GestoreEventi.event')),
            ],
        ),
    ]
