# Generated by Django 5.2.3 on 2025-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestoreEventi', '0006_event_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_adult_only',
            field=models.BooleanField(default=False, help_text='Check this if the event is for adults (18+) only', verbose_name='Adults only'),
        ),
    ]
